"""Static dictionaries used by the demo backend."""

SKILL_SEED = [
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "Kotlin",
    "Go",
    "Rust",
    "C++",
    "C#",
    "SQL",
    "React",
    "Vue",
    "FastAPI",
    "Django",
    "Spring Boot",
    "Docker",
    "Kubernetes",
    "Machine Learning",
    "Data Analysis",
    "UI/UX Design",
    "Figma",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Git",
]

ROLE_SEED = [
    "Backend Developer",
    "Frontend Developer",
    "Fullstack Developer",
    "Mobile Developer",
    "ML Engineer",
    "Data Scientist",
    "DevOps Engineer",
    "QA Engineer",
    "UI/UX Designer",
    "Project Manager",
    "Team Lead",
    "Security Engineer",
    "Data Engineer",
]
